language: node_js
node_js:
  - "4.2"
  - "5.0"

sudo: false

addons:
  ssh_known_hosts:
  - 192.241.218.94

branches:
  only:
    - task-travisDeploy

before_install:
  - openssl aes-256-cbc -K $encrypted_5b6e06e2bfa9_key -iv $encrypted_5b6e06e2bfa9_iv
    -in deploy_static.pem.enc -out deploy_static.pem -d

  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@3

script:
  - npm test
  - NODE_ENV=production node_modules/.bin/builder run build-static

after_success:
  # make sure key is permissive, but not too permissive
  - chmod 600 deploy_static.pem
  # clean out any existing staging folder but make sure it exists
  - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/builder-staging && mkdir static/builder-staging"
  # copy the builder build to the staging arena; if this fails, site is still OK
  - scp -i deploy_static.pem -rp ./build/* formidable@192.241.218.94:/home/formidable/static/builder-staging
  # rename the staging arena to the actual builder site
  - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/builder-test && mv static/builder-staging/ static/builder-test"
