language: node_js
node_js:
  - "4.2"
  - "5.0"

sudo: false

addons:
  ssh_known_hosts:
  - 192.241.218.94

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_5b6e06e2bfa9_key -iv $encrypted_5b6e06e2bfa9_iv
    -in deploy_static.pem.enc -out deploy_static.pem -d

  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install npmv3 because of postinstall bugs in npmv2:
  # See https://github.com/FormidableLabs/victory/issues/98
  # TODO REENABLE
  # - npm install -g npm@3

# TODO REMOVE -- Skip install for experiments!
install: true

script:
  - echo "TODO REENABLE npm test"
  - echo "TODO REENABLE NODE_ENV=production node_modules/.bin/builder run build-static"
  - echo "TODO REMOVE RUNNING DEPLOY SCRIPT IN PR MANUALLY"
  - ./deploy.sh

# Once build on Travis is working, automatically deploy it on master only:
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  # TODO REENABLE
  # on:
  #   branch: master
